export const RECEIVE_TWEETS='RECEIVE_TWEETS';
export const RECEIVE_USERS='RECIVE_USERS';
export const RECEIVE_AUTHED_USER='RECEIVE_AUTHED_USER';
export const TOGGLE_TWEET='TOGGLE_TWEET'; 
export const ADD_TWEET='ADD_TWEET'; 